=== NasC0/Telerik_HW_2013-2014/Databases/13. XmlProcessing/06.students-extended.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="urn:students"  attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="student">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="sex" type="xs:string" />
              <xs:element name="birthDate" type="xs:date" />
              <xs:element name="phone" type="xs:string" />
              <xs:element name="email" type="xs:string" />
              <xs:element name="course" type="xs:string" />
              <xs:element name="specialty" type="xs:string" />
              <xs:element name="facultyNumber" type="xs:string" />
              <xs:element name="enrollment">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="enrollmentDate" type="xs:date" />
                    <xs:element name="enrollmentScore" type="xs:decimal" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="exams">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="exam">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="examName" type="xs:string" />
                          <xs:element name="examScore" type="xs:decimal" />
                          <xs:element name="tutor">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="tutorName" type="xs:string" />
                                <xs:element name="endorsement" type="xs:unsignedShort" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== NasC0/Telerik_HW_2013-2014/Databases/13. XmlProcessing/05.students-extended.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="05.students-extended.xsl"?>
<students xmlns="urn:students"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xsi:schemaLocation="urn:students 06.students-extended.xsd">
  <student>
    <name>Pesho</name>
    <sex>Male</sex>
    <birthDate>1921-12-21</birthDate>
    <phone>0231-123-3412</phone>
    <email>Pesho@pesho.pesho</email>
    <course>Peshovshtina</course>
    <specialty>Pesho</specialty>
    <facultyNumber>FPESHO</facultyNumber>
    <enrollment>
      <enrollmentDate>2010-01-01</enrollmentDate>
      <enrollmentScore>35.2</enrollmentScore>
    </enrollment>
    <exams>
      <exam>
        <examName>PeshoExam</examName>
        <examScore>70.5</examScore>
        <tutor>
          <tutorName>Pesho tutor</tutorName>
          <endorsement>1000</endorsement>
        </tutor>
      </exam>
      <exam>
        <examName>PeshoExam</examName>
        <examScore>70.5</examScore>
        <tutor>
          <tutorName>Pesho tutor</tutorName>
          <endorsement>1000</endorsement>
        </tutor>
      </exam>
      <exam>
        <examName>PeshoExam</examName>
        <examScore>70.5</examScore>
        <tutor>
          <tutorName>Pesho tutor</tutorName>
          <endorsement>1000</endorsement>
        </tutor>
      </exam>
    </exams>
  </student>
  <student>
    <name>Pesho</name>
    <sex>Male</sex>
    <birthDate>1921-12-21</birthDate>
    <phone>0231-123-3412</phone>
    <email>Pesho@pesho.pesho</email>
    <course>Peshovshtina</course>
    <specialty>Pesho</specialty>
    <facultyNumber>FPESHO</facultyNumber>
    <enrollment>
      <enrollmentDate>2010-01-01</enrollmentDate>
      <enrollmentScore>35.2</enrollmentScore>
    </enrollment>
    <exams>
      <exam>
        <examName>PeshoExam</examName>
        <examScore>70.5</examScore>
        <tutor>
          <tutorName>Pesho tutor</tutorName>
          <endorsement>1000</endorsement>
        </tutor>
      </exam>
      <exam>
        <examName>PeshoExam</examName>
        <examScore>70.5</examScore>
        <tutor>
          <tutorName>Pesho tutor</tutorName>
          <endorsement>1000</endorsement>
        </tutor>
      </exam>
      <exam>
        <examName>PeshoExam</examName>
        <examScore>70.5</examScore>
        <tutor>
          <tutorName>Pesho tutor</tutorName>
          <endorsement>1000</endorsement>
        </tutor>
      </exam>
    </exams>
  </student>
</students>
